---
- hosts: webservers
  become: true
  tasks:
  - name: Stop Tomcat
    service: name=tomcatstop state=stopped
  - name: Check that war file exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
    register: stat_result

  - name: Delete the war file, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example.war
      state: absent
    when: stat_result.stat.exists == True
  - name: Check that GAMEOFLIFE dir exist
    stat:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
    register: stat_result
  - name: Delete the GAMEOFLIFE dir, if it exist already
    file:
      path: /usr/share/tomcat/webapps/hello-world-servlet-example
      state: absent
    when: stat_result.stat.exists == True
  - name: Deploy War File
    get_url:
       url: http://172.31.40.153:8081/#browse/browse:maven-releases:com%2Fgeekcap%2Fvmturbo%2Fhello-world-servlet-example%2F18%2Fhello-world-servlet-example-LATEST.war
       dest: /root/apache-tomcat-9.0.70/webapps
  - name: Start Tomcat
    service: name=tomcatstart state=started
